### ISSUE TITLE
APB command not showing anything

### ISSUE THREAD

**Issue by dhawan1997** [godbout/alfred-airpodspro-battery#1]
Although my airpods pro are connected to my mac. It isn't displaying any information 

<img width="710" alt="Screenshot 2021-04-09 at 4 23 33 PM" src="https://user-images.githubusercontent.com/82213570/114170054-fe216680-994f-11eb-985c-29f0a871b2e2.png">

It was working for a few days. Just today I had to boot my mac into safe mode and bring it to normal mode. Since then it has stopped working. I have tried re-installing alfred. re-installing the workflow. Restarting the computer. But nothing worked.

Could you kindly help/guide me to fix this? 🙏

**Comment by ruslaniv** [comment]
Same here

macOS 11.5.2
Retina 5K, 27 inch, 2019 iMac
Workflow 1.2.0

**Comment by godbout** [comment]
shit. seems i never got notifications for your comments.
i'm gonna release an update for Monterey in a few hours. could you please check and let me know?

**Comment by dhawan1997** [comment]
Hey Could you help me understand if I can update directly from Alfred or some other way? Also have you released the update?

**Comment by godbout** [comment]
you need to download the new release from GitHub. on the main page there's the releases on the right. but here you go: https://github.com/godbout/alfred-airpodspro-battery/releases/tag/2.0.0

download, double click, Alfred will update the Workflow and keep your settings. enjoy.

**Comment by ruslaniv** [comment]
Just updated to the latest version, it is still not working.

macOS 11.6 Big Sur 
Retina 5K, 27 inch, 2019 iMac
Workflow 2.0.0

**Comment by godbout** [comment]
![Release_2_0_0_·_godbout_alfred-airpodspro-battery](https://user-images.githubusercontent.com/121373/144005234-ff168733-f3a8-491e-8a3a-6a5f9c726cd6.jpg)

**Comment by godbout** [comment]
> Just updated to the latest version, it is still not working.
> 
> macOS 11.6 Big Sur Retina 5K, 27 inch, 2019 iMac Workflow 2.0.0

you need to use v1 if you're on Big Sur.

install v1, connect your AirPods, and then run in the terminal:
```system_profiler SPBluetoothDataType```

paste the output here so that i can have a look.

**Comment by mhoffmann777** [comment]
On 12.3 they changed the output again. 

Connected:
`Bluetooth:

      Bluetooth Controller:
          Address: XX:XX:XX
          State: On
          Chipset: BCM_4387
          Discoverable: Off
          Firmware Version: 19.5.432.4739
          Product ID: 0x0001
          Supported services: 0x382039 < HFP AVRCP A2DP HID Braille AACP GATT Serial >
          Transport: PCIe
          Vendor ID: 0x004C (Apple)
      Connected:
          AirPods Pro von Matthias:
              Address: XX:XX:XX
              Vendor ID: 0x004C
              Product ID: 0x200E
              Case Battery Level: 100 %
              Left Battery Level: 74 %
              Right Battery Level: 74 %
              Firmware Version: 4C165
              Minor Type: Headphones
              RSSI: -31
              Serial Number: H1XXXXXXXXX
              Services: 0x980019 < HFP AVRCP A2DP AACP GATT ACL >
          MX Keys Mac:
              Address: XX:XX:XX`

Not connected:
`Bluetooth:

      Bluetooth Controller:
      Connected:
          MX Keys Mac:
              Address: XX:XX:XX
      Not Connected:
          AirPods Pro von Matthias:
              Address: XX:XX:XX
              Vendor ID: 0x004C
              Product ID: 0x200E
              Firmware Version: 4C165
              Minor Type: Headphones
`

**Comment by godbout** [comment]
fuck. ok. annoying but at the same time their bluetooth never works properly so i guess the updates are needed lol

thanks. will check soon.

**Comment by godbout** [comment]
update: https://github.com/godbout/alfred-airpodspro-battery/releases/tag/3.0.0

if it works we can just close this issue. thanks.

**Comment by mhoffmann777** [comment]
Nice! Works for me again! :)

**Comment by godbout** [comment]
![baseball-eyebrows](https://user-images.githubusercontent.com/121373/160137041-5fb22333-33cf-4908-b297-6cc3bd1c26e6.gif)
