### ISSUE TITLE
Doesn't Work on MacOS 12.3

### ISSUE THREAD

**Issue by fw3i** [godbout/alfred-airpodspro-battery#3]
I connected my Airpods Pro but it showed not connected on MacOS 12.3.
<img width="764" alt="image" src="https://user-images.githubusercontent.com/40256755/160003735-b9538766-925e-412f-a666-bdedd17947fd.png">

<img width="346" alt="image" src="https://user-images.githubusercontent.com/40256755/160003840-b80b847e-6f98-4018-8214-bc8130605221.png">

**Comment by godbout** [comment]
why the fuck i don't receive notifications from GH. you're in luck, i stumble upon your issue by accident. i was just releasing an update for 12.3. they've change the bluetooth config again. here you go: https://github.com/godbout/alfred-airpodspro-battery/releases/tag/3.0.0

**Comment by fw3i** [comment]
It works now, thanks dude!
<img width="764" alt="image" src="https://user-images.githubusercontent.com/40256755/160137100-10ae604f-b77b-4057-a976-0d8e1ce10ea1.png">

**Comment by godbout** [comment]
actually i'm just hardcoded the levels. it will always show 100%.

just kidding. enjoy.

**Comment by yarub123** [comment]
@godbout dude this workflow works DELICIOUSLY. I didn't want to create an "issue" so I'm commenting here to say thank you, sincerely, for this amazing fucking work. Good shit brotha.

**Comment by godbout** [comment]
@yarub123 thank you brother. if you like utility tools, you may like my paid and free apps. good shits. but i'm biased 😂️
[kindaVim](https://github.com/godbout/kindaVim.docs), [Wooshy](https://github.com/godbout/Wooshy.docs) and [Scrolla](https://github.com/godbout/Scrolla.docs). have fun brother!

**Comment by yarub123** [comment]
@godbout Oh that's funny I haven't even checked your main page. You're the fuckin KindaVIM guy? ahaha, oddly enough I actually do have KindaVIM 😅. Didn't realize that was you. Small world. What are the fucking chances that some random dude from an airpod alfred workflow also happened to be the same guy behind another app I downloaded not too long ago. Life's a trip.

**Comment by godbout** [comment]
> @godbout Oh that's funny I haven't even checked your main page. You're the fuckin KindaVIM guy? ahaha, oddly enough I actually do have KindaVIM 😅. Didn't realize that was you. Small world. What are the fucking chances that some random dude from an airpod alfred workflow also happened to be the same guy behind another app I downloaded not too long ago.

not to diminish the funny coincidence, but for a decade i've released TONS OF SHITS in that area, utility/productivity stuff. so that raises the chances 😂️
 
> Life's a trip.

oh boy. fuck yeah.

**Comment by yarub123** [comment]
@godbout LOL yeah you have a point there, the chances def do increase ahaha. But it's just funny that the two world's collided... that being Vim and something kinda unrelated which is this workflow for Alfred... Though you're a Mac user (I'm assuming) and so def increased likelihood haha. Appreciate you.

**Comment by godbout** [comment]
yeah :D LIFE>IS>FUN!

**Comment by godbout** [comment]
> Though you're a Mac user (I'm assuming)

yeah. as far as i'm concerned if i drop the Mac i drop computers altogether.

**Comment by yarub123** [comment]
@godbout ahaha I feel the same way. Even though I'm against being a fanboy. But the OS itself is what keeps us coming back. Imagine having to exist on another OS... even with simple things like Window management or Alfred or BetterTouch. It's absurd. That is no life for me.

**Comment by godbout** [comment]
> @godbout ahaha I feel the same way. Even though I'm against being a fanboy. But the OS itself is what keeps us coming back. Imagine having to exist on another OS... even with simple things like Window management or Alfred or BetterTouch. It's absurd. That is no life for me.

yeah. same. never been a fanboy in anything. just using tools that are pleasurable (to me) while i build stuff. that includes paintings, music, software. as soon as i don't build any, i drop. but just building for computers is too much fun, and cheap. no raw material. can make a lot of mistakes 😅️ work from anywhere. little to carry etc. but yeah, if Apple fucks this up i'm fucked 🤣️🤣️🤣️
